name: bmcp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - pip=21.2.4
  - python-graphviz==0.17
  - pip:
    - arviz==0.11.2
    - ipython==7.26.0
    - jupyter==1.0.0
    - jupyterlab==3.2.1
    - matplotlib==3.4.3
    - mkl==2021.3.0
    - numpy==1.19.5
    - numpyro==0.7.2
    - pandas==1.3.2
    - pydot==1.4.2
    - pymc3==3.11.4
    - statsmodels==0.12.2
    - scipy==1.7.1
    - tensorflow_probability==0.15.0
    - tensorflow==2.7.0
    - theano-pymc==1.1.2
    - xarray== 0.19.0
