name: bmcp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - pip=21.2.4
  - python-graphviz==0.17
  - pip:
    - arviz==0.11.2
    - ipython==7.26.0
    - jupyter==1.0.0
    - matplotlib==3.4.3
    - mkl==2021.3.0
    - numpy==1.21.2
    - pandas== 1.3.2
    - pymc3==3.11.4
    - scipy==1.7.1
    - theano-pymc==1.1.2
    - xarray== 0.19.0
